### ISSUE TITLE
Error: Unable to connect to the database

### ISSUE THREAD

**Issue by subharanjanm** [michael-cannon/typo3-importer#6]
I've used your WP-Plugin "TYPO3 tt_news Importer", but it doesn't work. It shown: "Unable to connect to the database". But I know for sure, that the database-login-data are correct.

**Comment by subharanjanm** [comment]
This is happening because of `if ( ! is_resource( $t3db->dbh ) ) {` where it is always returning `false` even if the `$t3db->dbh` is an object. 

https://github.com/michael-cannon/typo3-importer/blob/master/settings.typo3-importer.php#L819

**Comment by MaverickVG** [comment]
same here! Any solution?

**Comment by subharanjanm** [comment]
Hi @MaverickVG , 

I'm sorry about the trouble.

This issue has already been fixed and the fix should be out in the next official release very soon.

In the meantime, could you please try the release candidate? https://github.com/michael-cannon/typo3-importer/archive/2.3.2RC1.zip

Thanks !!

**Comment by MaverickVG** [comment]
your RC worked, thank you very much!
